apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-gateway
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-gateway
  template:
    metadata:
      labels:
        app: secure-gateway
    spec:
      containers:
        - name: app
          image: ghcr.io/annie-7554/secure-gateway:latest
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
