apiVersion: v1
kind: Service
metadata:
  name: secure-gateway
  namespace: production
spec:
  selector:
    app: secure-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
